更改Hyperlink位置，添加新的Mods
EpsilonNetWorkGroup/SCCCPServerWiki pull request #33
Opened 2023-01-06 03:46 UTC by EnchantStudio

2023-01-06 05:23 UTC, Dmitri233 commented on docs/Mainc/mods.md
> +|[Fabric API](https://modrinth.com/mod/fabric-api)|为其他Mod提供支持|
你在一边更改链接位置与添加其他mod，将其分为两个提交以增加可读性

2023-01-06 05:23 UTC, Dmitri233 requested changes
将其分为两个提交以增加可读性

2023-01-06 06:37 UTC, EnchantStudio commented on docs/Mainc/mods.md
> +|[Fabric API](https://modrinth.com/mod/fabric-api)|为其他Mod提供支持|
不会

2023-01-06 06:38 UTC, EnchantStudio commented on docs/Mainc/mods.md
> +|[Fabric API](https://modrinth.com/mod/fabric-api)|为其他Mod提供支持|
怎么把一个提交拆成两个

2023-01-06 10:30 UTC, EnchantStudio commented
根本就是两个commits

2023-01-06 10:34 UTC, Dmitri233 approved these changes, later dismissed

2023-01-07 08:26 UTC, Dmitri233 approved these changes
@EnchantStudio

2023-01-07 13:52 UTC, merged